version: "2"

linters:
  default: none
  enable:
    - dupl
    - gochecknoinits
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
    govet:
      enable:
        - shadow
    revive:
      confidence: 0.1
    misspell:
      locale: US
    lll:
      line-length: 140
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: at least one file in a package should have a package comment
      - linters:
          - revive
        text: should have a package comment
      - linters:
          - gosec
        path: _test\.go
    paths:
      - vendor

run:
  timeout: 5m
  modules-download-mode: vendor
  relative-path-mode: gomod
